### ISSUE TITLE
Confusing IndexOutOfBounds Crash when running tests on Emulator 21

### ISSUE THREAD

**Issue by fknives** [fknives/Android-Tutorial-Test-ShowCase#108]
**Describe the bug**
Tests are not run properly and a weird IndexOutOfBounds crash happens

Logs:
```
*** FATAL EXCEPTION IN SYSTEM PROCESS: main
E/AndroidRuntime( 1499): java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
E/AndroidRuntime( 1499): 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:117)
E/AndroidRuntime( 1499): 	at android.view.accessibility.AccessibilityManager.handleNotifyAccessibilityStateChanged(AccessibilityManager.java:645)
E/AndroidRuntime( 1499): 	at android.view.accessibility.AccessibilityManager.access$000(AccessibilityManager.java:68)
E/AndroidRuntime( 1499): 	at android.view.accessibility.AccessibilityManager$MyHandler.handleMessage(AccessibilityManager.java:693)
E/AndroidRuntime( 1499): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1499): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1499): 	at com.android.server.SystemServer.run(SystemServer.java:269)
E/AndroidRuntime( 1499): 	at com.android.server.SystemServer.main(SystemServer.java:170)
E/AndroidRuntime( 1499): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1499): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1499): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 1499): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
D/gralloc_ranchu( 1128): gralloc_alloc: Creating ashmem region of size 819200
```

**Additional context**
It looks like the whole AndroidTesting process crashed, since not all tests are listed

[Emulator-Test-Results-21.zip](https://github.com/fknives/AndroidTest-ShowCase/files/9112312/Emulator-Test-Results-21.zip)

[Emulator-Logcat-Logs-21.zip](https://github.com/fknives/AndroidTest-ShowCase/files/9112311/Emulator-Logcat-Logs-21.zip)

**Comment by fknives** [comment]
[Emulator-21-logs-and-test-results-20220926.zip](https://github.com/fknives/AndroidTest-ShowCase/files/9648488/Emulator-21-logs-and-test-results-20220926.zip)
Additional logs ^
