### ISSUE TITLE
Flacky Compose screen test

### ISSUE THREAD

**Issue by fknives** [fknives/Android-Tutorial-Test-ShowCase#97]
**Describe the bug**
AuthComposeActivity Test sometimes fails.

**Expected behavior**
The test should always behave the same way

**Additional context**
Failed on Emulator 30
Logs from CI:
```kotlin
org.fnives.test.showcase.ui.AuthComposeInstrumentedTest > networkErrorShowsProperErrorMessage[test(AVD) - 11] FAILED 
	androidx.compose.ui.test.ComposeTimeoutException: Condition still not satisfied after 1000 ms
	at androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceTimeUntil$1.invoke(AbstractMainTestClock.kt:58)
org.fnives.test.showcase.ui.login.codekata.CodeKataAuthActivitySharedTest > null[test(AVD) - 11] SKIPPED 
Tests on test(AVD) - 11 failed: There was 1 failure(s).
Jul 12, 2022 7:26:56 AM com.google.testing.platform.RunnerImpl$Companion summarizeAndLogTestResult
SEVERE: Execute org.fnives.test.showcase.ui.AuthComposeInstrumentedTest.networkErrorShowsProperErrorMessage: FAILED
androidx.compose.ui.test.ComposeTimeoutException: androidx.compose.ui.test.ComposeTimeoutException: Condition still not satisfied after 1000 ms
at androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceTimeUntil$1.invoke(AbstractMainTestClock.kt:58)
at androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceTimeUntil$1.invoke(AbstractMainTestClock.kt:54)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread$lambda-0(AndroidSynchronization.android.kt:37)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.$r8$lambda$JHfZTn-RG8lrYeP9BZG_AgROyug(Unknown Source:0)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt$$ExternalSyntheticLambda0.call(Unknown Source:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:[266](https://github.com/fknives/AndroidTest-ShowCase/runs/7296766659?check_suite_focus=true#step:7:270))
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
androidx.compose.ui.test.ComposeTimeoutException: Condition still not satisfied after 1000 ms
at androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceTimeUntil$1.invoke(AbstractMainTestClock.kt:58)
at androidx.compose.ui.test.junit4.AbstractMainTestClock$advanceTimeUntil$1.invoke(AbstractMainTestClock.kt:54)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread$lambda-0(AndroidSynchronization.android.kt:37)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.$r8$lambda$JHfZTn-RG8lrYeP9BZG_AgROyug(Unknown Source:0)
at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt$$ExternalSyntheticLambda0.call(Unknown Source:2)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2223)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Test results saved as file:/Users/runner/work/AndroidTest-ShowCase/AndroidTest-ShowCase/app/build/outputs/androidTest-results/connected/test(AVD)%20-%2011/test-result.pb. Inspect these results in Android Studio by selecting Run > Import Tests From File from the menu bar and importing test-result.pb.
> Task :app:connectedDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
```

**Comment by fknives** [comment]
Similar thing also happened on API 21
```kotlin
org.fnives.test.showcase.ui.AuthComposeInstrumentedTest > emptyUserNameShowsProperErrorMessage[test(AVD) - 5.0.2] FAILED 
	java.lang.AssertionError: Failed to assert the following: (Text + EditableText contains 'Username is not filled properly!' (ignoreCase: false))
	Reason: Expected exactly '1' node but could not find any node that satisfies: (TestTag = 'AuthScreenTag.LoginError')
org.fnives.test.showcase.ui.login.codekata.CodeKataAuthActivitySharedTest > null[test(AVD) - 5.0.2] SKIPPED 
Tests on test(AVD) - 5.0.2 failed: There was 1 failure(s).
Jul 12, 2022 11:37:18 AM com.google.testing.platform.RunnerImpl$Companion summarizeAndLogTestResult
SEVERE: Execute org.fnives.test.showcase.ui.AuthComposeInstrumentedTest.emptyUserNameShowsProperErrorMessage: FAILED
java.lang.AssertionError: java.lang.AssertionError: Failed to assert the following: (Text + EditableText contains 'Username is not filled properly!' (ignoreCase: false))
Reason: Expected exactly '1' node but could not find any node that satisfies: (TestTag = 'AuthScreenTag.LoginError')
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:162)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:96)
at androidx.compose.ui.test.AssertionsKt.assert(Assertions.kt:268)
at androidx.compose.ui.test.AssertionsKt.assert$default(Assertions.kt:260)
at androidx.compose.ui.test.AssertionsKt.assertTextContains(Assertions.kt:214)
at androidx.compose.ui.test.AssertionsKt.assertTextContains$default(Assertions.kt:209)
at org.fnives.test.showcase.ui.ComposeLoginRobot.assertErrorIsShown(ComposeLoginRobot.kt:50)
at org.fnives.test.showcase.ui.AuthComposeInstrumentedTest.emptyUserNameShowsProperErrorMessage(AuthComposeInstrumentedTest.kt:100)
java.lang.AssertionError: Failed to assert the following: (Text + EditableText contains 'Username is not filled properly!' (ignoreCase: false))
Reason: Expected exactly '1' node but could not find any node that satisfies: (TestTag = 'AuthScreenTag.LoginError')
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:162)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:96)
at androidx.compose.ui.test.AssertionsKt.assert(Assertions.kt:268)
at androidx.compose.ui.test.AssertionsKt.assert$default(Assertions.kt:260)
at androidx.compose.ui.test.AssertionsKt.assertTextContains(Assertions.kt:214)
at androidx.compose.ui.test.AssertionsKt.assertTextContains$default(Assertions.kt:209)
at org.fnives.test.showcase.ui.ComposeLoginRobot.assertErrorIsShown(ComposeLoginRobot.kt:50)
at org.fnives.test.showcase.ui.AuthComposeInstrumentedTest.emptyUserNameShowsProperErrorMessage(AuthComposeInstrumentedTest.kt:100)
```

**Comment by fknives** [comment]
Additional instance in Splash Activity:
[Emulator-Test-Results-30.zip](https://github.com/fknives/AndroidTest-ShowCase/files/9092985/Emulator-Test-Results-30.zip)

**Comment by fknives** [comment]
Since the splash activity one is different, moved into a separate issue: https://github.com/fknives/AndroidTest-ShowCase/issues/99

**Comment by fknives** [comment]
[Emulator-Test-Results-30.zip](https://github.com/fknives/AndroidTest-ShowCase/files/9108822/Emulator-Test-Results-30.zip)

**Comment by fknives** [comment]
[Emulator-Test-Results-21.zip](https://github.com/fknives/AndroidTest-ShowCase/files/9109660/Emulator-Test-Results-21.zip)
